m = input('Digita alguma coisa ai:')
print('Tipo dele', type(m))
print('é alfanumerico?', m.isalnum())
print('é alfabetico?', m.isalpha())
print('', m.isascii())
print('é um digito?', m.isdigit())
print('está em minusculo?', m.islower())
print('é decimal?', m.isdecimal())
print('', m.isidentifier())
print('é numérico?', m.isnumeric())
print('é printável?', m.isprintable())
print('é um espaço?', m.isspace())
print('é um titulo?', m.istitle())
print('está em maiúsculo?', m.isupper())
