a = input('Digite algo ')
print('{} é um numero?'.format(a), a.isnumeric())
print('{} é alfabético?' .format(a), a.isalpha())
print('{} é alfanumérico?'.format(a), a.isalnum())
print('{} está em maiucula?'.format(a), a.isupper())
print('{} está em minuscula?'.format(a), a.islower())
print('{} está capitalizada?'.format(a), a.istitle())
